### ISSUE TITLE
Error when creating user. TypeError: msecs must be a number

### ISSUE THREAD

**Issue by ncareau** [ircanywhere/ircanywhere#275]
```
npm --version
2.14.7
```

```
node --version
v4.2.2
```

When creating a new user, the application return a red box error and i find this in the logs.

```
2015-11-06T04:43:05.102Z - error: TypeError: msecs must be a number
    at Object.exports.enroll (timers.js:152:11)
    at TLSSocket.Socket.setTimeout (net.js:306:12)
    at new SMTPResponse (/var/web/irc/node_modules/emailjs/smtp/response.js:66:11)
    at Object.exports.monitor (/var/web/irc/node_modules/emailjs/smtp/response.js:71:9)
    at Object.SMTP.connect (/var/web/irc/node_modules/emailjs/smtp/smtp.js:173:35)
    at Object.Client._connect (/var/web/irc/node_modules/emailjs/smtp/client.js:68:17)
    at Object.Client._poll (/var/web/irc/node_modules/emailjs/smtp/client.js:28:18)
    at /var/web/irc/node_modules/emailjs/smtp/client.js:102:21
    at Object.Message.valid (/var/web/irc/node_modules/emailjs/smtp/message.js:140:10)
    at Object.Client.send (/var/web/irc/node_modules/emailjs/smtp/client.js:83:14)
```

**Comment by pirogoeth** [comment]
Same issue here. Happens on latest `development` branch.

```
2016-03-21T03:34:10.108Z - error: TypeError: msecs must be a number
    at Object.exports.enroll (timers.js:152:11)
    at TLSSocket.Socket.setTimeout (net.js:306:12)
    at new SMTPResponse (/root/ircanywhere/node_modules/emailjs/smtp/response.js:66:11)
    at Object.exports.monitor (/root/ircanywhere/node_modules/emailjs/smtp/response.js:71:9)
    at Object.SMTP.connect (/root/ircanywhere/node_modules/emailjs/smtp/smtp.js:173:35)
    at Object.Client._connect (/root/ircanywhere/node_modules/emailjs/smtp/client.js:68:17)
    at Object.Client._poll (/root/ircanywhere/node_modules/emailjs/smtp/client.js:28:18)
    at /root/ircanywhere/node_modules/emailjs/smtp/client.js:102:21
    at Object.Message.valid (/root/ircanywhere/node_modules/emailjs/smtp/message.js:140:10)
    at Object.Client.send (/root/ircanywhere/node_modules/emailjs/smtp/client.js:83:14)
```

Server shuts down, but after bringing it back up, it appears that the user is still created successfully.

**Comment by ncareau** [comment]
Closing this issue, since i'm not using this anymore. And is probably fixed or at least not present anymore due to the large gap between node and npm version since i created this issue.
