### ISSUE TITLE
install.js: SyntaxError: Unexpected token "="

### ISSUE THREAD

**Issue by fnkr** [ircanywhere/ircanywhere#277]
What am I doing wrong?

```
/home/ubuntu/workspace/install.js:201
        function waitForRsInitiated(db, originalResult, waittime=30) {
                                                                ^
SyntaxError: Unexpected token =
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

[full log](https://gist.github.com/fnkr/1e75ffc7dde78dd5ac25)

**Comment by fnkr** [comment]
Found the reason: `install.js` adds `/usr/local/lib/node_modules` to `$PATH`, however, I'm using nvm so the correct path is `/home/ubuntu/.nvm/v0.10.41/lib/node_modules`.

**Comment by MatFluor** [comment]
I have the same problem on Debian (Turnkey Nodejs appliance). Tried with and without nvm (including the workaround from @fnkr) but it did not work; neither on Node 0.10.41 nor on nodejs 12.7.

Am I missing something here?

**Comment by zamabe** [comment]
Bad code. Some of my code was merged without testing.

**Comment by labsin** [comment]
Also get this error. Can this be reopened?

**Comment by mikrobyte** [comment]
Having the same issue :(
====================================================

leo@h2529749:/opt/ircanywhere$ sudo ./install.sh
[sudo] password for leo: 

/opt/ircanywhere/install.js:201
	function waitForRsInitiated(db, originalResult, waittime=30) {
	                                                        ^
SyntaxError: Unexpected token =
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

leo@h2529749:/opt/ircanywhere$ ls /usr/local/lib/node_modules/
nave  npm  pm2
leo@h2529749:/opt/ircanywhere$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

**Comment by seirl** [comment]
What's the status on this? Is there a way to quick-fix it?

**Comment by zamabe** [comment]
On Mar 16, 2016, "Antoine Pietri" <notifications@github.com> wrote:
>
> What's the status on this? Is there a way to quick-fix it?

Hand written, excuse numbering mistakes
.
install.js line 191

    - waitForRsInitiated(db, result);
    + waitForRsInitiated(db, result, 30);

install.js line 201

    - function waitForRsInitiated(db, originalResult, waittime=30) {
    + function waitForRsInitiated(db, originalResult, waittime) {

**Comment by zamabe** [comment]
```diff
--- a/install.js
+++ b/install.js
@@ -188,7 +188,7 @@ function isMongoRunning(isGlobal, path) {
                        
                db.command({replSetInitiate: null}, function(err, result) {
                        if (err === null || (result !== null && result.ok === 1)) {
-                               waitForRsInitiated(db, result);
+                               waitForRsInitiated(db, result, 30);
                        } else {
                                console.log(err, result);
                                console.log(COLOUR.red, 'rs.initiate() failed. Needs manual intervention.');
@@ -198,7 +198,7 @@ function isMongoRunning(isGlobal, path) {
        }
 
        // waittime is in seconds
-       function waitForRsInitiated(db, originalResult, waittime=30) {
+       function waitForRsInitiated(db, originalResult, waittime) {
                waittime = waittime * 2 // check every half-second, so double the count
 
                process.stdout.write(COLOUR.blue, 'Checking if the replica set is fully initiated...');
```

**Comment by zamabe** [comment]
```diff
--- a/install.js
+++ b/install.js
@@ -188,7 +188,7 @@ function isMongoRunning(isGlobal, path) {
                        
                db.command({replSetInitiate: null}, function(err, result) {
                        if (err === null || (result !== null && result.ok === 1)) {
-                               waitForRsInitiated(db, result);
+                               waitForRsInitiated(db, result, 30);
                        } else {
                                console.log(err, result);
                                console.log(COLOUR.red, 'rs.initiate() failed. Needs manual intervention.');
@@ -198,20 +198,17 @@ function isMongoRunning(isGlobal, path) {
        }
 
        // waittime is in seconds
-       function waitForRsInitiated(db, originalResult, waittime=30) {
-               waittime = waittime * 2 // check every half-second, so double the count
+       function waitForRsInitiated(db, originalResult, waittime) {
+               waittime = waittime * 2; // check every half-second, so double the count
+               success = 0;
 
                process.stdout.write(COLOUR.blue, 'Checking if the replica set is fully initiated...');
-               while (waittime => 0) {
-                       db.command({rs.status}, function(err, result) {
+               while (waittime > 0) {
+                       db.command({ 'rs.status': '' }, function(err, result) {
                                if (result.myState == 1) {
                                        process.stdout.write(' Success!\n');
-                                       break;
-                               } else if (waittime == 0) {
-                                       process.stdout.write('\n');
-                                       process.stdout.write(COLOUR.yellow, 'It appears that the mongodb replica set has not yet been initiated.');
-                                       process.stdout.write(COLOUR.yellow, 'MongoDB may magically correct this in seconds or minutes, but please be aware of this issue.');
-                                       break;
+                                       success = 1;
+                                       waittime = 0;
                                } else {
                                        waittime = waittime - 1;
                                        process.stdout.write('.');
@@ -219,6 +216,12 @@ function isMongoRunning(isGlobal, path) {
                                }
                        });
                }
+               if (success == 0) {
+                       process.stdout.write('\n');
+                       process.stdout.write(COLOUR.yellow, 'It appears that the mongodb replica set has not yet been initiated.');
+                       process.stdout.write(COLOUR.yellow, 'MongoDB may magically correct this in seconds or minutes, but');
+                       process.stdout.write(COLOUR.yellow, 'please be aware of this potential issue.');
+               }
                doneInstalling(db, originalResult);
        }
```

Of course, I still don't know if this will work. Particularly `db.command({ 'rs.status': '' }, ...`, because "selectors" aren't exactly documented. Pull request at your own risk. Last time I opened PR labeled 'untested code' it got accepted. Not going further down that rabbit hole.

**Comment by zamabe** [comment]
Maybe `{rs:{initiate}}`, but I have no idea. `rs.initiate()` works when feeding it through the shell. Don't know how to do it from node.
