### ISSUE TITLE
install.sh doesn't work

### ISSUE THREAD

**Issue by askl56** [ircanywhere/ircanywhere#281]
Trying to set up ircanywhere on a droplet, get this error when running install.sh:

```root@gitlab-2gb-ams3-01:/home/apps/ircanywhere# ./install.sh 
/home/apps/ircanywhere/install.js:206
			db.command({rs.status}, function(err, result) {
			              ^
SyntaxError: Unexpected token .
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
``` 

Any ideas?

**Comment by zamabe** [comment]
https://github.com/ircanywhere/ircanywhere/issues/277#issuecomment-173476227

**Comment by zamabe** [comment]
Also, the last commits to this project were 2 years ago. I am doubtful you should be attempting to use this, considering it never dropped its unstable status *before* the author's other priorities took precedent over this project considering it likely has many security issues which, if they were not known before, have likely been exposed over time.

**Comment by u-r-b-a-n-y** [comment]
Do you know if there is any alternative?

**Comment by DanielOaks** [comment]
@u-r-b-a-n-y May be worth looking towards this one instead: https://github.com/thelounge/lounge/

**Comment by dgw** [comment]
The Lounge is what I switched to. It's pretty great, and under quite active development. There have been three releases so far this year.
