### ISSUE TITLE
TypeError: Cannot read property 'ns' of null

### ISSUE THREAD

**Issue by joedborg** [ircanywhere/ircanywhere#283]
Running into this error on Ubuntu 16.04

```
$ node server/main.js 
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
SockJS v0.3.18 bound to "/websocket"
2017-02-16T11:12:06.351Z - warn: cannot bind identd server to port 113, disabling, you should run with elevated permissions or bind to a different port and forward with iptables
2017-02-16T11:12:06.353Z - info: IRC server listening on :: 6667
2017-02-16T11:12:06.374Z - error: TypeError: Cannot read property 'ns' of null
    at /home/joe/Projects/ircanywhere/server/app.js:230:24
    at /home/joe/Projects/ircanywhere/node_modules/mongodb/lib/mongodb/cursor.js:271:33
    at /home/joe/Projects/ircanywhere/node_modules/mongodb/lib/mongodb/cursor.js:778:35
    at Cursor.close (/home/joe/Projects/ircanywhere/node_modules/mongodb/lib/mongodb/cursor.js:1009:5)
    at Cursor.nextObject (/home/joe/Projects/ircanywhere/node_modules/mongodb/lib/mongodb/cursor.js:778:17)
    at commandHandler (/home/joe/Projects/ircanywhere/node_modules/mongodb/lib/mongodb/cursor.js:741:14)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at /home/joe/Projects/ircanywhere/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at bound (domain.js:287:14)
```

**Comment by joedborg** [comment]
```
$ node --version
v6.9.5
```

**Comment by zamabe** [comment]
Last commit on this project was 2015. Are you sure you should be requesting support?
